### ISSUE TITLE
100件以上のレコード更新時にエラー発生した場合に結果にエラーが表示されない

### ISSUE THREAD

**Issue by kiku38** [kintone-labs/cli-kintone#13]
100件以上のレコード更新時にエラーが発生した場合に、正常完了の結果と同じ表示となるためエラーで弾かれているレコードがあったことがわからない。

99件未満の場合は以下のエラーが表示される

レコードID重複
```
>cli-kintone -a 181 -d ***.cybozu.com -u okiku -p test  -e sjis -f  sample.csv
2017/02/23 19:33:25 AppError: 400 [GAIA_RE09] レコード（id: 100）の指定が重複しています。 (1505999166-1787320933)

>cli-kintone -a 181 -d ***.cybozu.com -u okiku -p test  -e sjis -f  sample.csv
2017/02/23 19:53:42 AppError: 400 [CB_VA01] 入力内容が正しくありません。 (1505999166-1788538719)
```

**Comment by wolftatsu** [comment]
該当コードを読んでみましたが、記載の通り100件以上の操作対象レコードがあった場合、終了直前の処理単位（100件）のエラーのみ表示し、それ以前のエラーは握りつぶしていますね。
仕様検討としては
- エラーを配列に保持しておいて、処理終了時にまとめて表示
- そもそもkintone APIの仕様が100件単位のリクエストなので、100件までしか受け付けない

いずれかの方法の検討かと思いますが、後者の場合はbulk処理のメリットが薄れてしまうので前者の対応かと。その場合、複数メッセージを良い感じで表示するlogライブラリがパッと調べた感じなさそうですね。自前で書くしかないのか。。。
ちょっと検討してみますが、妙案あれば教えてください m(_ _)m

**Comment by cy-kaneko** [comment]
ご報告、ありがとうございました。
V0.9.0で、100ずつ、結果を表示するように修正しました。
最新版のcli-kintoneをご使用ください。
