### ISSUE TITLE
READMEには、条件にあえば更新、なければ追加とあるが、追加されずエラーとなる

### ISSUE THREAD

**Issue by sTone3** [kintone-labs/cli-kintone#27]
### **Import specified file into an App**
If the import file has an $id column (or a field code for the Record number), records will be updated and/or added. If the value in $id matches a record number value, that record will be updated. **_It the value does not match, a new record will be added._**

## [実行結果]
```
$ cli-kintone.exe -a <APP_ID> -d <FQDN> -u <User's log in name> -p <User's password> -e sjis -f <INPUT_FILE>
[2018-01-22 09:56:30]: Start from lines: 1 - 100 => SUCCESS
[2018-01-22 09:56:34]: Start from lines: 101 - 200 => SUCCESS
[2018-01-22 09:56:38]: Start from lines: 201 - 300 => ERROR OCCURRED
ID:  ********************
Code:  GAIA_RE20
Status:  404 Not Found
Message:  「updateKey」に指定した条件にあてはまるレコードが見つかりません。
Errors detail: (none)

[2018-01-22 09:56:38]: PROCESS STOPPED!

UPDATE ERROR.
For error details, please read the details above.
Lines 201 to 300 of the imported file contain errors. Please fix the errors on t
he file, and re-import it with the flag "-l 201"


$ 
```

レコード番号以外の特定のフィールドでレコードを更新するために、CSVファイルのヘッダ行にあるフィールドコードの先頭に更新キーを表すマーク"*"をつけています。更新キーとなるフィールドは値の重複を禁止する設定にしました。

READMEに「値が一致しなければ新しいレコードを追加する」と書いてありますが、この挙動は違う気がします。
kintoneの「ファイルから読み込む」を使用したときの挙動と同じ結果を期待します。

ちなみに、CSVファイルのヘッダ行の「*」を外すと期待した挙動となりました。
（更新対象データがあれば更新、なければ追加する）
どこかにそのような記述がありますでしょうか。

**Comment by will-yama** [comment]
Thank you for submitting the issue.  
The readme has been edited to match how cli-kintone works.

**Comment by will-yama** [comment]
Sorry, looks like importing using $id and importing using key field (update_key) processes differently in cli-kintone.
The readme will be re-edited

**Comment by sTone3** [comment]
早速の対応ありがとうございます。
Thank you for your quick response.
