### ISSUE TITLE
We can't run cli-kintone from Mac OS under proxy environment.

### ISSUE THREAD

**Issue by TomokoMiyake** [kintone-labs/cli-kintone#32]
# Condition
1. Install the latest cli-kintone to the client PC

2. Set the proxy below on Mac terminal
export http_proxy={proxy url}
export https_proxy="${http_proxy}"
export HTTP_PROXY="${http_proxy}"
export HTTPS_PROXY="${http_proxy}"
export no_proxy=127.0.0.1,localhost

3. Run the cli-kintone
ex) ./cli-kintone -d bozuman -u {subdomain} -p password -a {appId}

# Result
The following error occurs.
Get {subdomain} http: error connecting to proxy {proxy url} : dial tcp: no suitable address found

*I have already checked this occurs on Mac PC. Maybe it will occur on another UNIX environment (I haven't checked yet).

# Possible causes
I guess the go version to build cli-kintone is the cause of it.
The detail of it is the below update on unix environment(src/net/dnsclient_unix.go). > DNS resolving of .local.
https://go-review.googlesource.com/c/go/+/27250
It's just unix update, so it doesn't occur on windows environment.

From the above, it depends on the go version, so could you try to re-build cli-kintone by latest go version(1.9.3)?
Thanks.

**Comment by cy-kaneko** [comment]
Fixes in v0.9.1
