### ISSUE TITLE
テーブルの一部の項目だけ指定して更新すると、指定していない項目がブランクで更新される

### ISSUE THREAD

**Issue by sugiyama-hirofumi** [kintone-labs/cli-kintone#40]
テーブルに項目A（必須）, 項目B, 項目Cがあり、すべてデータ入力済みの状態から
項目Bだけ指定して更新 => 項目Aが未入力扱いのエラー
項目A, 項目B指定して更新 => 項目Cがブランクで上書きされる

項目Bだけ指定している時は、restで項目A, 項目Bを設定しないようにしてほしいです

**Comment by dinh-van-tran** [comment]
Hi @sugiyama-hirofumi-gn san
I couldn't reproduce this issue. Could you provide more information about it?

1. Environment: Window, Linux or MacOS
2. Kintone app structure
3. Data: Is it created by cli-kintone export or manualy?
4. Run command

thanks

**Comment by sugiyama-hirofumi** [comment]
Hi @tranvan538 san

Sorry, do not enough information I wrote.
Please could you check this gist ?
https://gist.github.com/sugiyama-hirofumi-gn/b2cd4ef86247ebaa8dcd680b2dbdf6fa

Env is CentOS7.
Updated by cli-kintone.

Console result is

```
init
[2018-07-05 07:21:02]: Start from lines: 1 - 2 => SUCCESS
[2018-07-05 07:21:03]: DONE

before
*,"$id","$revision","Table","colTableA","colTableB","colTableC","colA"
*,"1","5","37390161","ta1","tb1","tc1","a1"
,"1","5","37390162","ta1","tb2","tc2","a1"
,"1","5","37390163","ta1","tb3","tc3","a1"

put1
[2018-07-05 07:21:03]: Start from lines: 1 - 2 => ERROR OCCURRED
ID:  kQfSZCw6S2jlBBYiQISV
Code:  CB_VA01
Status:  400 Bad Request
Message:  入力内容が正しくありません。
Errors detail:
  'records[0].Table.value[1].value.colTableA.value': 必須です。
  'records[0].Table.value[2].value.colTableA.value': 必須です。
  'records[0].Table.value[0].value.colTableA.value': 必須です。

[2018-07-05 07:21:03]: PROCESS STOPPED!

UPDATE ERROR.
For error details, please read the details above.
Lines 1 to 2 of the imported file contain errors. Please fix the errors on the file, and re-import it with the flag "-l 1"


after1
*,"$id","$revision","Table","colTableA","colTableB","colTableC","colA"
*,"1","5","37390161","ta1","tb1","tc1","a1"
,"1","5","37390162","ta1","tb2","tc2","a1"
,"1","5","37390163","ta1","tb3","tc3","a1"

put2
[2018-07-05 07:21:04]: Start from lines: 1 - 2 => SUCCESS
[2018-07-05 07:21:04]: DONE

after2
*,"$id","$revision","Table","colTableA","colTableB","colTableC","colA"
*,"1","6","37390164","ta1p","tb1p","","a1"
,"1","6","37390165","ta2p","tb2p","","a1"
,"1","6","37390166","ta3p","tb3p","","a1"
```

Is put1 error is bug ?
And the colTableC is updated with blanks.

thanks

**Comment by dinh-van-tran** [comment]
Thanks @sugiyama-hirofumi-gn san
We've been able to reproduce it. We will fix as soon as possible.

**Comment by dinh-van-tran** [comment]
Hi @sugiyama-hirofumi-gn san
- This issue **is not bug** cause by cli-kintone. This is the behavior of kintone rest api.

**Root cause**
- Each row in table has a id like record's id.

```
*,"$id","$revision","Table","colTableA","colTableB","colTableC","colA"
*,"1","5","37390161","ta1","tb1","tc1","a1"
,"1","5","37390162""ta1","tb2","tc2","a1"
,"1","5","37390163","ta1","tb3","tc3","a1"
```
- The rows id in above csv file is 37390161, 37390162, 37390163.
- When update data, the kintone service find row's id and update it.
- If the row's data isn't include in request or not found in service, the row will be deleted and be replace by new one.

**In this issue**
- when upload data_init.csv, the record's row id is missing.

```
*,*colA,colTableA,colTableB,colTableC
*,a1,ta1,tb1,tc1
,a1,ta1,tb2,tc2
,a1,ta1,tb3,tc3
```
- It should be

```
*,*colA,Table,colTableA,colTableB,colTableC
*,a1,37390161,ta1,tb1,tc1
,a1,37390162,ta1,tb2,tc2
,a1,37390163,ta1,tb3,tc3
```

**Comment by sugiyama-hirofumi** [comment]
Hi @tranvan538 san,

Thank you for investigating.
I got it, what kind of behavior it was.
This issue closed.

thanks
