### ISSUE TITLE
[v0.9.0 & v0.9.2] Column shift when exporting files in SJIS with UTF-8 characters that cannot be converted to SJIS

### ISSUE THREAD

**Issue by niki-cy** [kintone-labs/cli-kintone#41]
When using Cli-kintone version 0.9.0 or 0.9.2 and exporting in Shift-JIS, the column values are shifted if a field in the exported file contains characters such as "¾" that cannot be converted from UTF-8 to Shift-JIS. 

The issue can be recreated by:
_The following was performed with Windows 10 and Cli-kintone version 0.9.2_

1. Make an app with multiple fields. At least one should be a text-type field (Text, Text Area, etc). 
![01](https://user-images.githubusercontent.com/43398321/46854988-75d4b000-ce3d-11e8-8a03-1fae171fb2f9.PNG)
2. Create a record with a character like "¾" as one of the values in a text-type field. 
![02](https://user-images.githubusercontent.com/43398321/46855170-e8de2680-ce3d-11e8-80fe-9c56a4899c6b.PNG)
4. Using Cli-kintone version 0.9.0 or 0.9.2, enter in the following commands:
    _cli-kintone -d [domain URL] -a [App ID] -u [login name] -p [password] -e sjis > sample.csv_
5. Open the exported file in Excel.
![03](https://user-images.githubusercontent.com/43398321/46855202-fabfc980-ce3d-11e8-805e-1ef5622c9e10.PNG)
6. The columns are shifted, with two field values entering into a single field's column.
![04](https://user-images.githubusercontent.com/43398321/46855271-280c7780-ce3e-11e8-8d70-6bab9ed7782d.PNG)

**Comment by quocphien90** [comment]
@niki-cy 
It have been fixed on v0.9.3

Thanks
