### ISSUE TITLE
Deploy binaries automatically by travis-ci

### ISSUE THREAD

**Issue by ymmt2005** [kintone-labs/cli-kintone#7]
It is easy to deploy binaries on GitHub releases page via travis-ci:
https://docs.travis-ci.com/user/deployment/releases

Running go test on travis-ci is also a good idea.

A sample travis.yml for one of my projects is here:
https://github.com/cybozu-go/goma/blob/master/.travis.yml

**Comment by ymmt2005** [comment]
@USHIROSAKO さんにあげときます。

**Comment by ushirosako** [comment]
@ymmt2005 Thanks
Build supported by travis-ci.

**Comment by ushirosako** [comment]
Corresponding to the Travis-cl from [v0.7](https://github.com/kintone/cli-kintone/releases/tag/v0.7).
