### ISSUE TITLE
I want to lift the spec that can't upload files larger than 10MB. What is the impact?

### ISSUE THREAD

**Issue by k-masa2501** [kintone-labs/cli-kintone#84]
I am the developer of the kintone app.

I'm sorry to ask you a question here.

This tool cannot upload files larger than 10MB.

I'm using this tool to migrate data, but due to constraints, I'm doing more manual work.

I'm thinking of downloading this source code locally, removing the restrictions, and rebuilding.

What is the impact of removing the constraint, except that it takes a long time to upload?

**Comment by trung-doan** [comment]
@k-masa2501 
That's right, it might take a long time to upload.
In addition, there may be some performance problems of kintone if continuously uploading large files.
And we don't know the details of the impact because we haven't tested uploading files larger than 10MB.

Thank you for the question.
